language: elixir

branches:
  only:
      - main 
      - develop

matrix:
  include:
    - otp_release: 19.3
      elixir: 1.5.3
    - otp_release: 20.3
      elixir: 1.5.3

    - otp_release: 19.3
      elixir: 1.6.6
    - otp_release: 20.3
      elixir: 1.6.6

    - otp_release: 21.3
      elixir: 1.7.4

    - otp_release: 21.3
      elixir: 1.8.1

script:
  - MIX_ENV=test mix do compile, test --trace
