name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir: [1.9.4, 1.10.2, 1.12.3, 1.13.4, 1.14]
        otp: [22.2.8, 23.3.4, 24.3.4, 25.0]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    # Set vars for the cache step -------------------------------------------
    - name: Set mix file hash
      id: set_mix_hash
      run: >
          mix_hash="${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}"
          echo "::set-output name=mix_hash::$mix_hash"

    - name: Restore dependencies cache
      id: test-cache
      uses: actions/cache@v3
      with:
        path: >
          deps
          _build
        key: ${{ runner.os }}-test-mix-${{ steps.set_mix_hash.outputs.mix_hash }}
        restore-keys: ${{ runner.os }}-test-mix-

    - name: Install dependencies and compile
      run: mix do deps.get, deps.compile, compile

  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir: [1.9.4, 1.10.2, 1.12.3, 1.13.4, 1.14]
        otp: [22.2.8, 23.3.4, 24.3.4, 25.0]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      # Set vars for the cache step -------------------------------------------
      - name: Set mix file hash
        id: set_mix_hash
        run: >
          mix_hash="${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}"
          echo "::set-output name=mix_hash::$mix_hash"

      - name: Restore dependencies cache
        id: test-cache
        uses: actions/cache@v3
        with:
          path: >
            deps
            _build
          key: ${{ runner.os }}-test-mix-${{ steps.set_mix_hash.outputs.mix_hash }}
          restore-keys: ${{ runner.os }}-test-mix-

    # Get and build all the deps --------------------------------------------
      - name: Install Dependencies
        run: mix do deps.get, deps.compile, compile

      # Run the unit tests ----------------------------------------------------
      - name: Run unit tests
        run: mix test
